import google.generativeai as genai
from typing import List, Dict, Any, Optional
from app.utils import generate_rag_prompt
import os
from dotenv import load_dotenv

load_dotenv()

# Configure Google Generative AI
api_key = os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)
    # Initialize the generative model
    model = genai.GenerativeModel('gemini-2.5-flash')
else:
    # Create a mock model for testing purposes if no API key is provided
    model = None
    print("Warning: GEMINI_API_KEY not found. The generator will return mock responses.")


def get_agent_response(
    query: str,
    contexts: List[str] = None,
    selected_text: Optional[str] = None
) -> Dict[str, Any]:
    """
    Get response from Google's Gemini model with RAG context
    """
    # Generate the RAG prompt
    prompt = generate_rag_prompt(query, contexts or [], selected_text)

    if model is None:
        # Return a mock response if no API key is configured
        return {
            "response": f"Mock response for query: {query}. To get real responses, please set your GEMINI_API_KEY."
        }

    try:
        # Generate content using the model
        response = model.generate_content(prompt)

        # Extract the text response
        if response.text:
            return {
                "response": response.text.strip()
            }
        else:
            return {
                "response": "No response generated by the model"
            }
    except Exception as e:
        # Handle any errors from the API
        return {
            "response": f"Error generating response: {str(e)}"
        }